# Generated by Django 2.1.1 on 2018-09-17 13:51

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0009_alter_user_last_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
            ],
            options={
                'verbose_name': '社員情報',
                'verbose_name_plural': '社員情報',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='BuTable',
            fields=[
                ('buCode', models.AutoField(help_text='部コードを入力してください(0001など)', primary_key=True, serialize=False, verbose_name='部コード')),
                ('name', models.CharField(help_text='部名を入力してください', max_length=32, verbose_name='部名')),
            ],
            options={
                'verbose_name': '部門情報',
                'verbose_name_plural': '部門情報',
            },
        ),
        migrations.CreateModel(
            name='CalendarTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(help_text='休日を指定してください', null=True, unique=True, verbose_name='日付')),
                ('Remark', models.CharField(help_text='祝日名や夏休みなどを記入してください', max_length=128, null=True, verbose_name='備考')),
            ],
            options={
                'verbose_name': '休日カレンダー',
                'verbose_name_plural': '休日カレンダー',
            },
        ),
        migrations.CreateModel(
            name='HolidayKubunTable',
            fields=[
                ('kubunid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='土日，祝日，夏季休暇など', max_length=32, verbose_name='休暇区分名')),
            ],
            options={
                'verbose_name': '休暇区分',
                'verbose_name_plural': '休暇区分',
            },
        ),
        migrations.CreateModel(
            name='KaTable',
            fields=[
                ('kaCode', models.AutoField(help_text='課コードを入力してください(0001など)', primary_key=True, serialize=False, verbose_name='課コード')),
                ('name', models.CharField(help_text='課名を入力してくっださい', max_length=32, verbose_name='課名')),
                ('buCode', models.ForeignKey(help_text='課が所属する部コードを選択してください', on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.BuTable', verbose_name='所属部門')),
            ],
            options={
                'verbose_name': '課情報',
                'verbose_name_plural': '課情報',
            },
        ),
        migrations.CreateModel(
            name='OfficeTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='事務所ごとに休日カレンダーを指定できます', max_length=32, verbose_name='オフィス名')),
            ],
            options={
                'verbose_name': 'オフィス',
                'verbose_name_plural': 'オフィス',
            },
        ),
        migrations.CreateModel(
            name='PriceTable',
            fields=[
                ('tanka_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='社員の等級を設定します', max_length=32, verbose_name='単価名')),
                ('tanka', models.IntegerField(help_text='等級の時給単価を設定します', verbose_name='単価')),
            ],
            options={
                'verbose_name': '単価',
                'verbose_name_plural': '単価',
            },
        ),
        migrations.CreateModel(
            name='TimeCardTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('day', models.DateField()),
                ('start', models.TimeField(verbose_name='出社時間')),
                ('end', models.TimeField(verbose_name='退社時間')),
                ('employ_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name': 'タイムカード',
                'verbose_name_plural': 'タイムカード',
            },
        ),
        migrations.CreateModel(
            name='TransportExpense',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField()),
                ('expense', models.IntegerField(default=0, verbose_name='交通費')),
                ('start', models.CharField(max_length=128, verbose_name='出発地')),
                ('end', models.CharField(max_length=128, verbose_name='目的地')),
                ('kind', models.IntegerField(default=0)),
                ('status', models.IntegerField(default=0, help_text='審査承認のステータスを指定します', verbose_name='ステータス')),
                ('remark', models.CharField(max_length=256)),
                ('employee_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号')),
            ],
            options={
                'verbose_name': '交通費',
                'verbose_name_plural': '交通費',
            },
        ),
        migrations.CreateModel(
            name='WorkCodeTable',
            fields=[
                ('dummy_id', models.AutoField(primary_key=True, serialize=False)),
                ('work_code', models.CharField(max_length=32, null=True, unique=True, verbose_name='作番コード')),
                ('name', models.CharField(max_length=128, verbose_name='作業内容')),
            ],
            options={
                'verbose_name': '作業番号',
                'verbose_name_plural': '作業番号',
            },
        ),
        migrations.CreateModel(
            name='WorkDetailCodeTable',
            fields=[
                ('work_detail_code', models.CharField(max_length=32, primary_key=True, serialize=False)),
                ('contents', models.CharField(max_length=512)),
            ],
        ),
        migrations.CreateModel(
            name='WorkTable',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('work_time', models.FloatField()),
                ('time_card_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.TimeCardTable')),
                ('work_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.WorkCodeTable')),
                ('work_detail_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.WorkDetailCodeTable')),
            ],
            options={
                'verbose_name': '作業一覧',
                'verbose_name_plural': '作業一覧',
            },
        ),
        migrations.AddField(
            model_name='calendartable',
            name='kubunid',
            field=models.ForeignKey(help_text='休暇区分を指定します', on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.HolidayKubunTable', verbose_name='休暇区分'),
        ),
        migrations.AddField(
            model_name='calendartable',
            name='name',
            field=models.ForeignKey(help_text='カレンダーを適用するオフィスを選択します', on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.OfficeTable', verbose_name='オフィス名'),
        ),
        migrations.AddField(
            model_name='user',
            name='kaCode',
            field=models.ForeignKey(help_text='所属課を選択してください', null=True, on_delete=django.db.models.deletion.CASCADE, to='waterDropApp.KaTable', verbose_name='課コード'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions'),
        ),
    ]
