# Generated by Django 2.1.1 on 2018-09-17 07:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('waterDropApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='timecardtable',
            options={'verbose_name': 'タイムカード', 'verbose_name_plural': 'タイムカード'},
        ),
        migrations.AlterField(
            model_name='timecardtable',
            name='employ_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='社員番号'),
        ),
        migrations.AlterField(
            model_name='timecardtable',
            name='end',
            field=models.TimeField(verbose_name='退社時間'),
        ),
        migrations.AlterField(
            model_name='timecardtable',
            name='start',
            field=models.TimeField(verbose_name='出社時間'),
        ),
    ]
