# Generated by Django 2.1.1 on 2018-09-17 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('waterDropApp', '0002_auto_20180917_1644'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timecardtable',
            name='month',
        ),
        migrations.RemoveField(
            model_name='timecardtable',
            name='year',
        ),
        migrations.AlterField(
            model_name='timecardtable',
            name='day',
            field=models.DateField(),
        ),
    ]
